### ISSUE TITLE
Revive the newsletter!

### ISSUE THREAD

**Issue by jamesmunns** [rust-embedded/blog#121]
It's time to revive the newsletter! @hargonix and @eldruin, let's coordinate here to get a post out this weekend, and get back to some regularity :)

**Comment by hargoniX** [comment]
I'd say we should definitely go through everything that was added to https://github.com/rust-embedded/awesome-embedded-rust since the last newsletter since it should be pretty easy thanks to git.

**Comment by kalkyl** [comment]
Count me in

**Comment by jamesmunns** [comment]
@hargoniX it would be great to have a list of all of the added items in the diff! Since it's been so long, it might make sense to have a couple "catch up" newsletter issues (maybe once a week?), instead of having one HUGE post. Once we catch up with the open items, we can return back to a monthly cadence.

If anyone is able to collect the list of new items, we can start working through adding a few words for each item for the blog post.

Let me know what you think!

**Comment by hargoniX** [comment]
The diff to 8d8cd4b480cb29f59b0a565c3b9d3cf9caa04f15 which is the first commit made after the last blog post shows:

* The RTFM -> RTIC renaming

**Resources**
* phil's OS blog being addded https://os.phil-opp.com/
* my little blog post on embedded driver writing being added https://hboeving.dev/blog/rust-2c-driver-p1/

**Tooling**
* the probe-rs tooling (cargo-flash, cargo-embed)
* cargo-u2f for " A small cargo subcommand to download cargo builds to Microsoft UF2 bootloaders via HID USB"

**Bindings**
* FreeRTOS-rust as RTOS bindings (not to be confused with FreeRTOS.rs)

**PACs**
* msp430fr2355 PAC being added
* ambiq-apollo1-pac, ambiq-apollo2-pac and ambiq-apollo3p-pac being added

**HALs**
* msp430fr2x5x-hal being added

**BSPs**
* a BSP for the onebitsy: https://crates.io/crates/onebitsy
* Several Adafruit BSPs: metro_m0, pygamer, feather-f405 , feather_m0, feather_m4, circuit_playground_express, edgebadge, gemma_m0, itsybitsy_m0, itsybitsy_m4, trinket_m0
* Several arduino BSPs: arduino_mkrvidor4000 , arduino_mkrzero, arduino_nano33iot
* The samd21_mini BSP 
* The xiao_m0 BSP

**General abstraction crates**
* The atat crate for parsing AT commands

**Drivers**
* ADXL313
* AnyLeaf
* dht-sensor
* MAX6955
* MCP25LCXX
* TC72
* ST7789
* DW1000
* Adafruit-7segment
**WIP Drivers**
* BMI160
* epd-waveshare
* HRS3300
* HDC20xx
* ISL29125
* LSM9DS1
* ltr-559
* lvgl
* MAX170xx
* MAX3010x
* MCP4725
* MLX9061x
* ublox-cellular-rs

**no_std crates**
* debouncr
* embedded-crc-macros
* embedded-websocket
* endian_codec
* gdbstub
* microfft
* smbus-pec

IMHO we (at least) should mention
* the probe-rs tooling
* the possibility to run async code on embedded devices
* the fact that rust can be compiled for AVR with the official rustc now
* maybe the new knurling efforts by Ferrous
* maybe the RTFM -> RTIC renaming

as well as things I'm sure I missed out on.

**Comment by jacobrosenthal** [comment]
cargo-hf2 to upload to uf2 bootloaders like most adafruit boards :)

**Comment by eldruin** [comment]
How do we want to split the list? Chronologically?
For my drivers/libs I can write something myself, of course.

**Comment by hargoniX** [comment]
So looking at the old news letter seems to me like the drivers aren't mentioned per name at all, everything else such as BSPs, libs, HALs etc does get a mention in the embedded projects section, plus we also need to agree on a set of highlights to include.

Chronological does sound reasonable to me, also given the fact that most of the new items are drivers or WIP drivers I'm not quite sure whether the catch up newsletter would be that huge? It seems like a rather reasonable amount to me when excluding the naming of all drivers like we already do anyways.

**Comment by jamesmunns** [comment]
So, what do y'all think of this as a plan:

1. We put out a newsletter that is basically, "we're back! Here's a big list of everything that has changed since the last update, and we'll spotlight some of these over the next weeks. Don't forget to submit your projects *here* for us to spotlight!"
2. For the next 3-4 articles, we mix in more details about some of the projects that were added, and any new submissions people have
3. Then we return to regular monthly posts.

If that sounds good, I'll write up the intro paragraph that says the stuff in 1. above, and a placeholder stub for the first article in 2., and we can get the post shipped for tomorrow!

**Comment by therealprof** [comment]
Sounds great to me.

**Comment by hargoniX** [comment]
To me as well!

**Comment by jamesmunns** [comment]
Added #122 to cover tomorrows release! Help needed to get it ready for release :)

**Comment by jamesmunns** [comment]
Hey y'all! I'm planning another release tonight. Got caught up more than I'd hoped this weekend/day, but we should be able to get the newsletter out!

**Comment by eldruin** [comment]
Today we should make a new release. At the moment it contains only 2 entries, though.
Is there anything else we could add?

BTW, is it time to close this issue?

**Comment by jamesmunns** [comment]
We should probably close this issue.

If any of you have time to run down the [RustEmbedded Twitter](https://twitter.com/rustembedded) for the last month or so, I've retweeted a lot of cool stuff we could add to the newsletter.

Happy to help get an issue out today/early this week!

**Comment by eldruin** [comment]
Oops the new release never happened. I do not think I will have time to go through the twitter feed, though :/

**Comment by eldruin** [comment]
Closing after #143
