### ISSUE TITLE
Editorial Idea: The Embedded Rust that Could Be

### ISSUE THREAD

**Issue by jamesmunns** [rust-embedded/blog#26]
Holding issue for an opinion piece on what is good and bad about embedded development in Rust, and what needs to change/grow/iterate to make the whole experience better.

**Comment by therealprof** [comment]
What I especially like about the Rust 2018 edition is how easy it is to get started with embedded development thanks to batteries-included and rustup: With a few commands (clicks?) any OS can turn into a fully functional embedded development system automatically and within minutes (or hours if you have very slow internet connection); there's no other universal free development environment which features that. Similarly if you have access to the source of a crate you'd like to try, cargo makes it absolutely hassle free to compile it with a single command.
