### ISSUE TITLE
Ideas for blog posts

### ISSUE THREAD

**Issue by japaric** [rust-embedded/blog#4]
We have a blog now! :tada:

It would be good to have content on it besides the biweekly newsletters. Here
are some ideas for blog posts that I could write.

- A call to action during RC1 talking about what the 2018 edition release means
  for the embedded Rust community (i.e. embedded Rust on stable; the beginning
  not the end; etc). Here we would encourage people to use *beta* to do embedded
  development. By the time this post goes out it should be possible to build
  no_std binaries on beta, and the book should have its first two chapters (how
  to get started) done.

- Officially announce [`cargo-binutils`]. v0.1.2 will be more user friendly (see
  the second half of
  https://github.com/rust-embedded/cargo-binutils/pull/20#issue-210971420) and
  we should let more people know about it.

[`cargo-binutils`]: https://github.com/rust-embedded/cargo-binutils

- "`global_asm!` on stable with this one weird trick". A blog post about [this
  trick] of shipping pre-assembled object files instead of .asm files that get
  assembled on the build machine. Using external assembly files is a know
  workaround for `global_asm!` (and `asm!` in some cases) but this trick doesn't
  required $prefix-gcc to be installed on the build machine. (Or this could 
  directly go into the book / embedonomicon)

@rust-embedded/all Opinions on the above ideas? Have suggestions for other blog
posts?

**Comment by therealprof** [comment]
@japaric Sounds great to me. I'd also like to propose that except for "behind the scenes" we also put up some a little bit more hands-on reads like how to easily solve some tricky practical problems, e.g. how to share an I2C bus between multiple drivers: https://crates.io/crates/shared-bus 😉
