### ISSUE TITLE
Zmu -Emulator for Microcontroller Systems

### ISSUE THREAD

**Issue by jjkt** [rust-embedded/blog#41]
For you consideration for a upcoming newsletter, I've been slowly working on a emulator called "zmu" targeting microcontroller based systems.

See:
- https://github.com/jjkt/zmu
- https://www.reddit.com/r/rust/comments/aypgcy/zmu_emulator_for_microcontroller_systems/

It's not totally awesome yet, but I think has potential to become a useful tool.

**Comment by jamesmunns** [comment]
Hey @jjkt, would you mind adding this as a PR to the repo?

You can either fork the repo and make a PR editing `content/2019-03-20-newsletter-17.md`, or [click here](https://github.com/rust-embedded/blog/edit/master/content/2019-03-20-newsletter-17.md) to edit online.

I'm very excited to see this published!

**Comment by jamesmunns** [comment]
Closed by #42
